#!/usr/bin/env bash
# Command to make an nginx server listen on port 80 with the fix short and sweet
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
